version: 1

loggers:
  root:
    level: DEBUG
    handlers:
      - screen
      - file

formatters:
  simple:
    format: "%(asctime)s [%(levelname)s] %(name)s: %(message)s"
  verbose:
    format: "[%(asctime)s] %(levelname)s [%(name)s %(funcName)s (%(lineno)d)]: %(message)s"

handlers:
  file:
    class: logging.handlers.TimedRotatingFileHandler
    when: midnight
    backupCount: 5
    formatter: verbose
    filename: yggy.log
    level: WARNING
  screen:
    class: logging.StreamHandler
    formatter: simple
    level: DEBUG
    stream: ext://sys.stdout